### ISSUE TITLE
Automated selection of the first suggestion on Google Trends

### ISSUE THREAD

**Issue by Noyoy** [pat310/google-trends-api#66] opened 2017-06-25 18:23 UTC
Hey There,
I'm using Google-Trends-Api to pull data on some research termes of mine. 
I noticed that the first suggestion has stronger results than my 'Search Terme'.
How can I automatically select the first suggestion?

**Comment by pat310** [comment] 2017-06-26 15:02
Hi @Noyoy.  Can you provide a code example of the query you are making?

**Comment by Noyoy** [comment] 2017-06-26 17:39
Hi @pat310, this is the code I'm using: 
```js
var googleTrendsApi = require("google-trends-api")
var fs = require('fs');

var park = ["Olympic National Park", "Gateway National Recreation Area", "George Washington Memorial Parkway", "Grand Canyon National Park"];

// park.forEach(getGoolge);
getAll(park,0)
function getAll(park, current){

  park[current] && getGoolge(park[current]).then(()=>{
    getAll(park, current + 1);
  });
}

function getGoolge(park_name) {
  return googleTrendsApi.interestOverTime({ keyword: park_name, startTime: new Date('2004-01-01'), endTime: new Date('2017-01-01'), geo:'US'})
    .then(function (res) {
      saveFile(park_name, res)
    })
    .catch(function (err) {
      console.error(err);
    });
};

function saveFile(name, text) {
  fs.writeFile(name + ".txt", text, function (err) {
    if (err) {
      return console.log(err);
    }
    console.log("The file was saved! with name: " + name);
  });

}
```

**Comment by turnerniles** [comment] 2017-06-28 01:23
@Noyoy Can you paste the results and clarify what the issue is with the results?

**Comment by Noyoy** [comment] 2017-06-29 08:37
Hi @turnerniles, the results' output (from the API) is correct, 
My problem is, as you can see in the link, that I can have much stronger results by picking the first suggestion on the search bar. A thing that I can not do with google-trends-api.
In the [link](https://trends.google.com/trends/explore?q=%2Fm%2F02x9l_,Gates%20of%20the%20Arctic%20National%20Park%20and%20Preserve) I example how the results behaves, under the same keywords: 'Gates of the Arctic National Park and Preserve', comparing 'Search term' and 'National park'.

Cheers.

**Comment by Noyoy** [comment] 2017-07-07 03:59
Can anyone suggest me where I can ask such a question?
Thanks.

**Comment by pat310** [comment] 2017-07-07 12:20
Hi Noyoy! Could you use the '.relatedTopics' or '.relatedQueries' method to pull the top related result and then use 'interestOverTime' on that?

**Comment by pat310** [comment] 2017-07-07 12:28
There also used to be a method called 'risingsearches' which may be more inline with what you are looking for. You can check [back in the commit history](https://github.com/pat310/google-trends-api/blob/52ef10adf1db4a6749bc2ab82e0e5776d9d432f3/README.md#risingsearches) to see if it is what you are looking for and how that was implemented

**Comment by pat310** [comment] 2017-08-18 13:58
Closing this for now

**Closed by pat310** 2017-08-18 13:58 UTC
